markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "Rakefile"]
title : DSP Platform Documentation

baseurl: /dsp-platform-docs
date: 2015
author: Ontotext
ASSET_PATH : assets/boddhi

collections:
  v1_2_0-docs:
    output: true
  v1_1_1-docs:
    output: true
  v1_1_0-docs:
    output: true
